service: backend-latest
frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

useDotenv: true
 
provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 2048
  stage: dev
  timeout: 25
  region: us-east-1


#Serverless Functions
functions:
  server:
    handler: handler.latestApp
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      PORT: ${env:PORT}
      TOKEN_SECRET: ${env:TOKEN_SECRET}
      SESSION_SECRET: ${env:SESSION_SECRET}
      DB_USER: ${env:DB_USER}
      DB_HOST: ${env:DB_HOST}
      DB_NAME: ${env:DB_NAME}
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_PORT: ${env:DB_PORT}
      S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}