

service: backend-latest

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1

functions:
  hello:
    handler: handler.latestApp
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      PORT: 8000
      TOKEN_SECRET: mySecretKey
      SESSSION_SECRET: mySecretKey
      DB_USER: postgres
      DB_HOST: filler-db.crsimsmo0tl9.us-east-1.rds.amazonaws.com
      DB_NAME: postgres
      DB_PASSWORD: 765765fErari
      DB_PORT: 5432
      S3_BUCKET_NAME: codig-task-upload-s3
